### ISSUE TITLE
Unclear how to create new tokens

### ISSUE THREAD

**Issue by jcramer** [simpleledger/electrum#19]
Multiple users asking how to create new tokens.

There should be more clear UI direction, and add "Create a new token" to the tools dropdown menu.

**Comment by cculianu** [comment]
I agree.  I actually said something about this earlier at the 11th hour
before release.  I think that tab could maybe have a QToolBar and some
QToolBarButtons or something as addional UI cues.

**Comment by jcramer** [comment]
Maybe
